image: barichello/godot-ci:4.4
# Fonte: https://github.com/aBARICHELLO/godot-ci/blob/master/.gitlab-ci.yml#L16-L58
# NOTE: If your `project.godot` is at the repository root, set `PROJECT_PATH` below to ".".

# Cache imported assets between runs
cache:
  key: import-assets
  paths:
    - .godot/imported/

stages:
  - import-assets
  - export
  - deploy

variables:
  EXPORT_NAME: Tabuleiro_protótipo

# Open the editor to import assets in case the cache was empty or outdated
import-assets:
  stage: import-assets
  script:
    - godot --headless --verbose --import

# linux:
#   stage: export
#   script:
#     - mkdir -v -p build/linux
#     - EXPORT_DIR="$(readlink -f build)"
#     - godot --headless --verbose --export-release "Linux" "$EXPORT_DIR/linux/$EXPORT_NAME.x86_64"
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/linux

# windows:
#   stage: export
#   script:
#     - mkdir -v -p build/windows
#     - EXPORT_DIR="$(readlink -f build)"
#     - godot --headless --verbose --export-release "Windows Desktop" "$EXPORT_DIR/windows/$EXPORT_NAME.exe"
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/windows

# mac:
#   stage: export
#   script:
#     - mkdir -v -p build/mac
#     - EXPORT_DIR="$(readlink -f build)"
#
#     - godot --headless --verbose --export-release "macOS" "$EXPORT_DIR/mac/$EXPORT_NAME.zip"
#   artifacts:
#     name: $EXPORT_NAME-$CI_JOB_NAME
#     paths:
#       - build/mac

web:
  stage: export
  script:
    - mkdir -v -p build/web
    - EXPORT_DIR="$(readlink -f build)"
    - godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/web


pages:
  stage: deploy
  dependencies:
    - web
  script:
    #- git checkout pages
    #- rm -f *.md
    - mv build/web/** ./public
  pages: true
  artifacts:
    paths:
      - public
